"""Seed data for Tierra Organic Bistro menu (from leggimenu.it)."""

CATEGORIES = [
    {
        "slug": "colazione",
        "name": "Colazione",
        "description": "Inizia la giornata con ingredienti biologici, freschi e genuini.",
        "image_url": "https://images.unsplash.com/photo-1638720772346-b745bcd72f5f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "order": 1,
    },
    {
        "slug": "pranzo-cena",
        "name": "Pranzo / Cena",
        "description": "Poke bowls, ceviche e piatti del giorno preparati con materie prime di stagione.",
        "image_url": "https://images.unsplash.com/photo-1759922222212-3657d43bd5b5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "order": 2,
    },
    {
        "slug": "aperitierra",
        "name": "Aperitierra",
        "description": "Taglieri curati e drink d'autore. Tutti i giorni dalle 18:00 alle 20:00.",
        "image_url": "https://images.unsplash.com/photo-1559847844-5315695dadae?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "order": 3,
    },
    {
        "slug": "caffetteria",
        "name": "Caffetteria",
        "description": "Miscele biologiche, tisane e piccola pasticceria.",
        "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "order": 4,
    },
    {
        "slug": "bevande",
        "name": "Bevande",
        "description": "Selezione di bevande alcoliche e analcoliche, vini naturali e succhi freschi.",
        "image_url": "https://images.unsplash.com/photo-1544145945-f90425340c7e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "order": 5,
    },
    {
        "slug": "contorno",
        "name": "Contorno",
        "description": "Piccole aggiunte per completare il tuo piatto.",
        "image_url": "https://images.unsplash.com/photo-1757332051150-a5b3c4510af8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "order": 6,
    },
]

ITEMS = [
    # Colazione
    {
        "category_slug": "colazione",
        "name": "Avocado Toast",
        "description": "Pane bio integrale al miso, tostato e completato con avocado fresco e un filo di olio EVO. Un equilibrio raffinato, leggero e contemporaneo. Aggiunte disponibili: scrambled eggs, ceviche di salmone, ceviche di tonno e verdure, hummus.",
        "price": 15.00,
        "image_url": "https://images.unsplash.com/photo-1638720772346-b745bcd72f5f?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": None,
        "order": 1,
    },
    {
        "category_slug": "colazione",
        "name": "Pasticceria",
        "description": "Cornetti, muffin e dolci da forno artigianali, preparati ogni mattina con farine biologiche.",
        "price": 2.50,
        "image_url": "https://images.unsplash.com/photo-1509365465985-25d11c17e812?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": None,
        "order": 2,
    },
    # Pranzo / Cena
    {
        "category_slug": "pranzo-cena",
        "name": "Poke Media Bowl",
        "description": "Base 150gr, verdure 150gr, proteina 130gr. Una proteina a scelta (carne o veggie) e mix di verdure di stagione.",
        "price": 13.00,
        "image_url": "https://images.unsplash.com/photo-1759922222212-3657d43bd5b5?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": "Il più scelto",
        "order": 1,
    },
    {
        "category_slug": "pranzo-cena",
        "name": "Poke Grande Bowl",
        "description": "Base 200gr, verdure 180gr, proteina 180gr. Una proteina a scelta (carne o veggie) e mix di verdure di stagione.",
        "price": 15.00,
        "image_url": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": "Consigliato dallo Chef",
        "order": 2,
    },
    {
        "category_slug": "pranzo-cena",
        "name": "Catalana Mista",
        "description": "Classica catalana di pesce e crostacei con pomodorini, cipolla rossa di Tropea e agrumi.",
        "price": 17.00,
        "image_url": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": None,
        "order": 3,
    },
    {
        "category_slug": "pranzo-cena",
        "name": "Secondo con Contorno",
        "description": "Secondo del giorno accompagnato da un contorno di stagione.",
        "price": 17.00,
        "image_url": "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": None,
        "order": 4,
    },
    {
        "category_slug": "pranzo-cena",
        "name": "Zuppa Inkas",
        "description": "Zuppa peruviana tradizionale con verdure, legumi e spezie delicate.",
        "price": 17.00,
        "image_url": "https://images.unsplash.com/photo-1547592180-85f173990554?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": None,
        "order": 5,
    },
    {
        "category_slug": "pranzo-cena",
        "name": "Poke Bowl Media Pesce Mixto",
        "description": "Pesce fresco del giorno, almeno tre varietà, base e verdure di stagione.",
        "price": 18.00,
        "image_url": "https://images.unsplash.com/photo-1611143669185-af224c5e3252?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": None,
        "order": 6,
    },
    {
        "category_slug": "pranzo-cena",
        "name": "Poke Bowl Grande Pesce Mixto",
        "description": "Pesce fresco del giorno, almeno tre varietà, porzione abbondante con base e verdure di stagione.",
        "price": 24.00,
        "image_url": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": None,
        "order": 7,
    },
    {
        "category_slug": "pranzo-cena",
        "name": "Chicken & Curry with Rice and Veggies",
        "description": "Pollo al curry con riso basmati e verdure saltate.",
        "price": 18.00,
        "image_url": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": "Piatto del giorno",
        "order": 8,
    },
    {
        "category_slug": "pranzo-cena",
        "name": "Beef Stew with Red Wine and Pistacchio",
        "description": "Spezzatino di manzo brasato al vino rosso con granella di pistacchio.",
        "price": 22.00,
        "image_url": "https://images.unsplash.com/photo-1608500218890-c4f9019eb045?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": "Piatto del giorno",
        "order": 9,
    },
    {
        "category_slug": "pranzo-cena",
        "name": "Red Tuna Ceviche with Avocado",
        "description": "Ceviche di tonno rosso marinato con lime, avocado fresco e coriandolo.",
        "price": 20.00,
        "image_url": "https://images.unsplash.com/photo-1625944525533-473f1b3d9684?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": "Piatto del giorno",
        "order": 10,
    },
    {
        "category_slug": "pranzo-cena",
        "name": "Proteina Extra",
        "description": "Porzione extra di proteina a scelta.",
        "price": 3.00,
        "image_url": None,
        "badge": None,
        "order": 11,
    },
    {
        "category_slug": "pranzo-cena",
        "name": "Porzione Riso",
        "description": "Porzione aggiuntiva di riso basmati biologico.",
        "price": 5.00,
        "image_url": None,
        "badge": None,
        "order": 12,
    },
    # Aperitierra
    {
        "category_slug": "aperitierra",
        "name": "Tagliere Aperitivo",
        "description": "Carne, vegetariano o pesce + tempura di verdure di stagione + focaccia al rosmarino, hummus, pomodorini con marmellata di cipolla rossa. Include drink: cocktail, calice di vino bianco/rosso o prosecco.",
        "price": 15.00,
        "image_url": "https://images.unsplash.com/photo-1559847844-5315695dadae?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": "18:00 – 20:00",
        "order": 1,
    },
    {
        "category_slug": "aperitierra",
        "name": "Tagliere di Salumi e Formaggi",
        "description": "Culaccia di prosciutto crudo, mortadella di Prato, prosciutto cotto arrostito toscano, capocollo di Martina Franca, blu di mozzarella di bufala, Grana 16 mesi, cacio.",
        "price": 25.00,
        "image_url": "https://images.unsplash.com/photo-1541529086526-db283c563270?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "badge": None,
        "order": 2,
    },
    # Caffetteria
    {"category_slug": "caffetteria", "name": "Caffè", "description": "Miscela 100% arabica biologica.", "price": 1.20, "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?crop=entropy&cs=srgb&fm=jpg&q=85&w=900", "badge": None, "order": 1},
    {"category_slug": "caffetteria", "name": "Cappuccino", "description": "Espresso con latte fresco biologico e schiuma vellutata.", "price": 1.60, "image_url": "https://images.unsplash.com/photo-1572442388796-11668a67e53d?crop=entropy&cs=srgb&fm=jpg&q=85&w=900", "badge": None, "order": 2},
    {"category_slug": "caffetteria", "name": "Ginseng", "description": "Bevanda al ginseng, energizzante e naturale.", "price": 1.40, "image_url": None, "badge": None, "order": 3},
    {"category_slug": "caffetteria", "name": "Orzo", "description": "Orzo tostato, alternativa delicata al caffè.", "price": 1.20, "image_url": None, "badge": None, "order": 4},
    {"category_slug": "caffetteria", "name": "Tisana", "description": "Selezione di tisane biologiche: zenzero-limone, rooibos, menta, camomilla.", "price": 3.50, "image_url": None, "badge": None, "order": 5},
    {"category_slug": "caffetteria", "name": "Biscotto", "description": "Biscotto artigianale ai cereali integrali.", "price": 1.50, "image_url": None, "badge": None, "order": 6},
    # Bevande
    {"category_slug": "bevande", "name": "Calice di Vino Bianco", "description": "Selezione di vini naturali biologici.", "price": 6.00, "image_url": None, "badge": None, "order": 1},
    {"category_slug": "bevande", "name": "Calice di Vino Rosso", "description": "Selezione di vini naturali biologici.", "price": 6.00, "image_url": None, "badge": None, "order": 2},
    {"category_slug": "bevande", "name": "Calice di Prosecco", "description": "Prosecco DOC.", "price": 5.00, "image_url": None, "badge": None, "order": 3},
    {"category_slug": "bevande", "name": "Centrifugato del Giorno", "description": "Frutta e verdura fresca di stagione.", "price": 5.00, "image_url": None, "badge": None, "order": 4},
    {"category_slug": "bevande", "name": "Acqua Naturale 0,5L", "description": "", "price": 2.00, "image_url": None, "badge": None, "order": 5},
    # Contorno
    {"category_slug": "contorno", "name": "Slides", "description": "Verdure grigliate di stagione, leggere e saporite.", "price": 5.00, "image_url": "https://images.unsplash.com/photo-1757332051150-a5b3c4510af8?crop=entropy&cs=srgb&fm=jpg&q=85&w=900", "badge": None, "order": 1},
]
